const wordList = [
     { word: "sun", hint: "A star we see every day.", definition: "The Sun provides light and heat to Earth." },
    { word: "moon", hint: "Earth’s natural satellite.", definition: "The Moon orbits the Earth." },
    { word: "water", hint: "A liquid essential for life.", definition: "Water is necessary for survival." },
    { word: "tree", hint: "A tall green plant.", definition: "Trees provide oxygen and shade." },
    { word: "book", hint: "Used for reading.", definition: "Books contain information and stories." },
    { word: "pen", hint: "Used for writing.", definition: "A pen writes using ink." },
    { word: "school", hint: "A place for learning.", definition: "Schools educate students." },
    { word: "teacher", hint: "A person who teaches.", definition: "Teachers guide students." },
    { word: "food", hint: "We eat it.", definition: "Food gives energy." },
    { word: "milk", hint: "A white drink.", definition: "Milk is rich in calcium." },
    { word: "road", hint: "Used for travel.", definition: "Roads connect places." },
    { word: "city", hint: "A large town.", definition: "Cities have many people." },
    { word: "animal", hint: "A living being.", definition: "Animals can move and eat." },
    { word: "bird", hint: "An animal that flies.", definition: "Birds have wings." },
    { word: "fish", hint: "Lives in water.", definition: "Fish breathe through gills." },
    { word: "clock", hint: "Shows time.", definition: "A clock measures time." },
    { word: "rain", hint: "Falls from clouds.", definition: "Rain waters plants." },
    { word: "game", hint: "Played for fun.", definition: "Games provide entertainment." },
    { word: "music", hint: "Pleasant sound.", definition: "Music relaxes the mind." },
    { word: "ball", hint: "Used in sports.", definition: "Balls are used in many games." },
     { word: "planet", hint: "Orbits a star.", definition: "A planet moves around a star." },
    { word: "oxygen", hint: "Needed for breathing.", definition: "Oxygen supports life." },
    { word: "computer", hint: "An electronic device.", definition: "Computers process data." },
    { word: "internet", hint: "A global network.", definition: "The internet connects devices worldwide." },
    { word: "keyboard", hint: "Used to type.", definition: "A keyboard inputs text." },
    { word: "mountain", hint: "A high landform.", definition: "Mountains rise above land." },
    { word: "river", hint: "Flows with water.", definition: "Rivers move toward seas." },
    { word: "history", hint: "Study of the past.", definition: "History records events." },
    { word: "science", hint: "Study of nature.", definition: "Science explains the world." },
    { word: "gravity", hint: "Pulls objects down.", definition: "Gravity attracts objects." },
    { word: "weather", hint: "Day-to-day climate.", definition: "Weather includes rain and sun." },
    { word: "continent", hint: "Large landmass.", definition: "Earth has seven continents." },
    { word: "electricity", hint: "Powers devices.", definition: "Electricity provides energy." },
    { word: "transport", hint: "Moves people.", definition: "Transport includes vehicles." },
    { word: "language", hint: "Used for communication.", definition: "Languages express thoughts." },
    { word: "education", hint: "Process of learning.", definition: "Education builds knowledge." },
    { word: "culture", hint: "Traditions of people.", definition: "Culture reflects lifestyle." },
    { word: "currency", hint: "Used to buy things.", definition: "Currency is money." },
    { word: "population", hint: "Number of people.", definition: "Population counts people." },
    { word: "environment", hint: "Surroundings.", definition: "Environment supports life." },
    { word: "democracy", hint: "Rule by people.", definition: "Democracy allows public voting." },
    { word: "constitution", hint: "Supreme law.", definition: "A constitution defines rules." },
    { word: "civilization", hint: "Advanced society.", definition: "Civilizations develop culture." },
    { word: "industrialization", hint: "Growth of industries.", definition: "Industrialization increases production." },
    { word: "globalization", hint: "World connection.", definition: "Globalization links economies." },
    { word: "biodiversity", hint: "Variety of life.", definition: "Biodiversity supports ecosystems." },
    { word: "photosynthesis", hint: "Plants make food.", definition: "Photosynthesis uses sunlight." },
    { word: "revolution", hint: "Major change.", definition: "Revolutions reshape society." },
    { word: "architecture", hint: "Building design.", definition: "Architecture shapes structures." },
    { word: "philosophy", hint: "Study of thought.", definition: "Philosophy explores ideas." },
    { word: "economics", hint: "Study of money.", definition: "Economics studies production." },
    { word: "technology", hint: "Applied science.", definition: "Technology solves problems." },
    { word: "communication", hint: "Sharing information.", definition: "Communication connects people." },
    { word: "literature", hint: "Written works.", definition: "Literature expresses ideas." },
    { word: "psychology", hint: "Study of mind.", definition: "Psychology studies behavior." },
    { word: "astronomy", hint: "Study of space.", definition: "Astronomy studies stars." },
    { word: "mathematics", hint: "Numbers and logic.", definition: "Mathematics solves problems." },
    { word: "electricity", hint: "Energy flow.", definition: "Electricity powers machines." },
    { word: "geography", hint: "Study of Earth.", definition: "Geography studies land." },
    { word: "engineering", hint: "Design and build.", definition: "Engineering creates solutions." }
];